tests oper push - change origin should work
make -j clean sr_clean test_clean all && gdb tests/test_oper_push -ex r

978.022699 [508147][140737348721408][DBG]: Applying "operational" datastore changes success.
978.023595 [508147][140737348721408][DBG]: No "operational" datastore changes to apply.
978.023871 [508147][140737348721408][DBG]: Applying "operational" datastore changes success.
"<test-state xmlns="urn:sysrepo:mixed-config" xmlns:or="urn:ietf:params:xml:ns:yang:ietf-origin" or:origin="or:intended">
  <ll or:origin="or:default">a1</ll>
</test-state>
" != "<test-state xmlns="urn:sysrepo:mixed-config" xmlns:or="urn:ietf:params:xml:ns:yang:ietf-origin" or:origin="or:intended">
  <ll or:origin="or:dynamic">a1</ll>
</test-state>
"
[   LINE   ] --- opensource/sysrepo/tests/test_oper_push.c:2650: error: Failure!
Program received signal SIGABRT, Aborted.